### ISSUE TITLE
Both Pulling new update OR Cloning new version has issue

### ISSUE THREAD

**Issue by lethanhtrung2020** [arrowjs/CMS#20]
Hi,
I test new update by  
  git pull 

and re-clone new version by
  git clone

but keep old configuration file (database.js, redis.js and env\development.js)
## but both have error 

info: Application started on port 8000 , Process ID: 8870
Unhandled rejection SequelizeDatabaseError: column "type" does not exist
    at Query.formatError (/home/CMS/node_modules/arrowjs/node_modules/sequelize/lib/dialects/postgres/query.js:347:14)
    at null.<anonymous> (/home/CMS/node_modules/arrowjs/node_modules/sequelize/lib/dialects/postgres/query.js:81:19)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Query.handleError (/home/CMS/node_modules/arrowjs/node_modules/pg/lib/query.js:108:8)
    at null.<anonymous> (/home/CMS/node_modules/arrowjs/node_modules/pg/lib/client.js:171:26)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/home/CMS/node_modules/arrowjs/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
##     at TCP.onread (net.js:523:20)

Is there any change in DB structure?
Thanks

**Comment by thangtyt** [comment]
Hi,
The new version of CMS is changed DB structure. You must add column "type" (character varying) in table arr_category.
If you still have error about DB and you don't need to keep data, you can delete all tables of current database or create a new database then change config to use new database.
Let try this and feedback if you still exist errors.

**Comment by lethanhtrung2020** [comment]
Thanks, I try to clone a new nodejs server from lastest version of ArrowCMS and connect to old redis & postgres db.
After adding type column into arr_category table, the site is up and running and the menu is appeared.
But admin panel has no left menu. Access to a old post, screen show NO PERMISSION.
Note that I am using 2 nodejs servers loadbalanced by a ngixn server and 1 server running redis and postgres (4 servers in total) and all servers are restarted.
Contact me for futher detail system and testing information
![arr2](https://cloud.githubusercontent.com/assets/14961790/12219353/b49ac3d6-b772-11e5-9b02-3c9bf2fae1c0.png)

**Comment by TechMaster** [comment]
Please help our user install smoothly. He can use, others will use.

Cuong,
